/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontFamily: {
      gamay: ["gamay", "sans-serif"],
      gamaywide: ["gamay-wide", "sans-serif"],
      soleil: ["soleil", "sans-serif"],
      azo: ["azo-sans-web", "sans-serif"],
      azouber: ["azo-sans-uber", "sans-serif"],
      area: ["area-normal"],
      greycliff: ["greycliff-cf", "sans-serif"],
    },
    extend: {
      colors: {
        lightest: "#f5f4f0",
        "pris-purple": "#988BFA",
        "pris-pink": "#b6bcfa",
        "pris-light-pink": "#F1C2FF",
        "third-pink": "#fab6da",
        "pris-blue": "#B1DFFF",
        "pris-yellow": "#F8D283",
        "extra-yellow": "#ffe2a8",
        "extra-blue": "#a3d6ff",
        backwhite: "#f0eeeb",
        "third-blue": "#c5cffc",
        "second-blue": "#dfc5fc",
        "third-pink": "#F2C0CF",
        "second-pink": "#fcc5fc",
      },
      keyframes: {
        slideInRight: {
          "0%": { transform: "translate(-200%, 0)", opacity: 0 },
          "100%": { transform: "translate(0, 0)", opacity: 1 },
        },
        slideInLeft: {
          "0%": { transform: "translate(200%, 0)", opacity: 0 },
          "100%": { transform: "translate(0, 0)", opacity: 1 },
        },
        slideInBot: {
          "0%": { transform: "translate(0, 200%)", opacity: 0 },
          "100%": { transform: "translate(0, 0)", opacity: 1 },
        },
        arrow: {
          "0%, 100%": { transform: "translate(2px, 0px)" },
          "80%": { transform: "translate(-2px, 0px) scale(1.1)" },
        },
        fadeIn: {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
        gradient: {
          "0%": { backgroundPosition: "0% 50%" },
          "100%": { backgroundPosition: "100% 50%" },
        },
        blob: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "100%": { transform: "translate(0px, 0px) scale(1)" },
        },
        slideInTop: {
          "0%": { transform: "translate(0, -400%)", opacity: 0 },
          "100%": { transform: "translate(0, 0)", opacity: 1 },
        },
        float1: {
          "0%": { transform: "translate(0, 0)" },
          "10%": { transform: "translate(2px, -2px)" },
          "20%": { transform: "translate(-4px, 2px)" },
          "30%": { transform: "translate(3px, -1px)" },
          "40%": { transform: "translate(-2px, 4px)" },
          "50%": { transform: "translate(4px, -2px)" },
          "60%": { transform: "translate(-3px, 1px)" },
          "70%": { transform: "translate(2px, -4px)" },
          "80%": { transform: "translate(-1px, 3px)" },
          "90%": { transform: "translate(3px, -3px)" },
          "100%": { transform: "translate(0, 0)" },
        },
        float2: {
          "0%": { transform: "translate(0, 0)" },
          "10%": { transform: "translate(-2px, 2px)" },
          "20%": { transform: "translate(4px, -2px)" },
          "30%": { transform: "translate(-3px, 1px)" },
          "40%": { transform: "translate(2px, -4px)" },
          "50%": { transform: "translate(-4px, 2px)" },
          "60%": { transform: "translate(3px, -1px)" },
          "70%": { transform: "translate(-2px, 4px)" },
          "80%": { transform: "translate(1px, -3px)" },
          "90%": { transform: "translate(-3px, 3px)" },
          "100%": { transform: "translate(0, 0)" },
        },
        float3: {
          "0%": { transform: "translate(0, 0)" },
          "10%": { transform: "translate(1px, -1px)" },
          "20%": { transform: "translate(-2px, 1px)" },
          "30%": { transform: "translate(2px, -2px)" },
          "40%": { transform: "translate(-1px, 2px)" },
          "50%": { transform: "translate(3px, -3px)" },
          "60%": { transform: "translate(-2px, 1px)" },
          "70%": { transform: "translate(1px, -2px)" },
          "80%": { transform: "translate(-1px, 3px)" },
          "90%": { transform: "translate(2px, -2px)" },
          "100%": { transform: "translate(0, 0)" },
        },
        float4: {
          "0%": { transform: "translate(0, 0)" },
          "10%": { transform: "translate(-1px, 1px)" },
          "20%": { transform: "translate(2px, -1px)" },
          "30%": { transform: "translate(-2px, 2px)" },
          "40%": { transform: "translate(1px, -2px)" },
          "50%": { transform: "translate(-3px, 3px)" },
          "60%": { transform: "translate(2px, -1px)" },
          "70%": { transform: "translate(-1px, 2px)" },
          "80%": { transform: "translate(1px, -3px)" },
          "90%": { transform: "translate(-2px, 2px)" },
          "100%": { transform: "translate(0, 0)" },
        },
        buttonGrow: {
          "0%": { transform: "scale(1)" },
          "100%": { transform: "scale(1.05)" },
        },
      },
      animation: {
        float1: "float1 12s ease-in-out infinite",
        float2: "float2 12s ease-in-out infinite",
        float3: "float3 12s ease-in-out infinite",
        float4: "float4 12s ease-in-out infinite",
        buttonGrow: "buttonGrow 0.5s ease-out forwards",
        slideInRight: "slideInRight .7s ease-in-out forwards",
        slideInLeft: "slideInLeft .7s ease-in-out forwards",
        slideInBot: "slideInBot .7s ease-in-out forwards",
        arrow: "arrow infinite .8s ease-in-out",
        slideInTop: "slideInTop .5s ease-in-out forwards",
        gradient: "gradient 6s linear infinite",
        blob: "blob 7s infinite",
        fade: "fadeIn .4s ease-in-out",
      },
    },
  },
  plugins: [],
};
